#!/usr/bin/env ruby

path = ARGV.fetch(0) do
  warn "usage: verify-homebrew-cask.rb PATH"
  exit 2
end

begin
  cask = File.read(path)
rescue Errno::ENOENT => error
  warn "Homebrew cask policy: cannot read #{path}: #{error.message}"
  exit 1
end

template = <<~'CASK'
  # This file was generated by GoReleaser. DO NOT EDIT.
  cask "trello-cli" do
    version "__VERSION__"

    on_macos do
      on_intel do
        sha256 "__SHA__"
        url "https://github.com/abigotado/trello-cli/releases/download/__TAG__/trello-cli_#{version}_darwin_amd64.tar.gz"
      end
      on_arm do
        sha256 "__SHA__"
        url "https://github.com/abigotado/trello-cli/releases/download/__TAG__/trello-cli_#{version}_darwin_arm64.tar.gz"
      end
    end

    on_linux do
      on_intel do
        sha256 "__SHA__"
        url "https://github.com/abigotado/trello-cli/releases/download/__TAG__/trello-cli_#{version}_linux_amd64.tar.gz"
      end
      on_arm do
        sha256 "__SHA__"
        url "https://github.com/abigotado/trello-cli/releases/download/__TAG__/trello-cli_#{version}_linux_arm64.tar.gz"
      end
    end

    name "trello-cli"
    desc "Manage Trello from the command line, or from an AI agent shelling out to it"
    homepage "https://github.com/abigotado/trello-cli"

    livecheck do
      skip "Auto-generated on release."
    end

    binary "trello-cli"

    # No zap stanza required

  end
  CASK

pattern = Regexp.escape(template)
pattern.gsub!("__VERSION__", "[0-9A-Za-z][0-9A-Za-z.+-]*")
pattern.gsub!("__TAG__", "v[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?")
pattern.gsub!("__SHA__", "[0-9a-f]{64}")

unless Regexp.new("\\A#{pattern}\\z").match?(cask)
  warn "Homebrew cask policy: #{path} is not the exact non-executable GoReleaser cask structure"
  exit 1
end

puts "Homebrew cask policy ok"
