#!/usr/bin/env ruby

require "minitest/autorun"
require "open3"
require "tempfile"

class VerifyHomebrewCaskTest < Minitest::Test
  VERIFIER = File.join(__dir__, "verify-homebrew-cask.rb")
  SHA = "a" * 64
  VALID_CASK = <<~CASK
    # This file was generated by GoReleaser. DO NOT EDIT.
    cask "trello-cli" do
      version "0.2.2"

      on_macos do
        on_intel do
          sha256 "#{SHA}"
          url "https://github.com/abigotado/trello-cli/releases/download/v0.2.2/trello-cli_\#{version}_darwin_amd64.tar.gz"
        end
        on_arm do
          sha256 "#{SHA}"
          url "https://github.com/abigotado/trello-cli/releases/download/v0.2.2/trello-cli_\#{version}_darwin_arm64.tar.gz"
        end
      end

      on_linux do
        on_intel do
          sha256 "#{SHA}"
          url "https://github.com/abigotado/trello-cli/releases/download/v0.2.2/trello-cli_\#{version}_linux_amd64.tar.gz"
        end
        on_arm do
          sha256 "#{SHA}"
          url "https://github.com/abigotado/trello-cli/releases/download/v0.2.2/trello-cli_\#{version}_linux_arm64.tar.gz"
        end
      end

      name "trello-cli"
      desc "Manage Trello from the command line, or from an AI agent shelling out to it"
      homepage "https://github.com/abigotado/trello-cli"

      livecheck do
        skip "Auto-generated on release."
      end

      binary "trello-cli"

      # No zap stanza required

    end
  CASK

  def verify(cask)
    Tempfile.create(["trello-cli", ".rb"]) do |file|
      file.write(cask)
      file.flush
      _stdout, stderr, status = Open3.capture3("ruby", VERIFIER, file.path)
      return [status.success?, stderr]
    end
  end

  def test_accepts_the_generated_non_executable_structure
    success, stderr = verify(VALID_CASK)

    assert success, stderr
  end

  def test_rejects_an_obfuscated_quarantine_hook
    hook = <<~'RUBY'
        postflight do
          command = "xa" + "ttr"
          attribute = ["com", "apple", "quarantine"].join(".")
          system_command command, args: ["-d", attribute, staged_path]
        end
    RUBY
    cask = VALID_CASK.sub(%(  binary "trello-cli"\n), %(  binary "trello-cli"\n\n#{hook}))

    success, stderr = verify(cask)

    refute success
    assert_includes stderr, "is not the exact non-executable GoReleaser cask structure"
  end
end
