// Command gencommands renders the agent-facing command reference from the
// cobra tree.
//
// internal/cli is the single source of truth for the command surface. Writing
// this by hand is how ~30 commands drift from the binary within a week, and an
// agent reading a stale reference calls a flag that no longer exists.
package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/abigotado/trello-cli/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// pflagFlag aliases pflag.Flag so the visitor signatures read cleanly.
type pflagFlag = pflag.Flag

// generatedNotice marks the output as machine-produced, matching the
// convention the gofmt hook and the contract generator already use.
const generatedNotice = "<!-- Code generated by tools/gencommands. DO NOT EDIT. -->"

type flagInfo struct {
	Name      string
	Shorthand string
	Type      string
	Default   string
	Usage     string
}

type leafInfo struct {
	Path        string
	Short       string
	Flags       []flagInfo
	Mutates     bool
	Destructive bool
	Requires    []string
	RequiresOne []string
	Args        string
}

// collect walks the command tree.
//
// The tree must come from NewRootCommand and nothing else. Execute,
// InitDefaultHelpCmd, and InitDefaultCompletionCmd all inject commands at run
// time, so calling any of them would put `help` and `completion` into a
// reference describing this tool's surface. A cobra upgrade is what makes that
// matter, and dependabot proposes those.
func collect(root *cobra.Command) ([]flagInfo, []leafInfo) {
	var globals []flagInfo
	root.PersistentFlags().VisitAll(func(f *pflagFlag) {
		if f.Hidden {
			return
		}
		globals = append(globals, describeFlag(f))
	})
	sort.Slice(globals, func(i, j int) bool { return globals[i].Name < globals[j].Name })

	var leaves []leafInfo
	var walk func(*cobra.Command)
	walk = func(cmd *cobra.Command) {
		for _, sub := range cmd.Commands() {
			if skipCommand(sub) {
				continue
			}
			if sub.HasSubCommands() {
				walk(sub)
				continue
			}
			leaves = append(leaves, describeLeaf(sub))
		}
	}
	walk(root)
	sort.Slice(leaves, func(i, j int) bool { return leaves[i].Path < leaves[j].Path })
	return globals, leaves
}

func skipCommand(cmd *cobra.Command) bool {
	if cmd.Hidden || cmd.IsAdditionalHelpTopicCommand() {
		return true
	}
	switch cmd.Name() {
	case "help", "completion":
		return true
	}
	return false
}

func describeLeaf(cmd *cobra.Command) leafInfo {
	leaf := leafInfo{
		Path:        cmd.CommandPath(),
		Short:       cmd.Short,
		Mutates:     cmd.Annotations["mutates"] == "true",
		Destructive: cmd.Annotations["destructive"] == "true",
		Requires:    splitAnnotation(cmd.Annotations["requires"]),
		RequiresOne: splitAnnotation(cmd.Annotations["requires_one_of"]),
	}
	// cmd.Use is "default <account>" — the leaf name plus its argument spec.
	// Only the spec is wanted here; the full path comes from CommandPath.
	if _, spec, found := strings.Cut(cmd.Use, " "); found && strings.Contains(spec, "<") {
		leaf.Args = spec
	}

	inherited := cmd.InheritedFlags()
	local := cmd.LocalFlags()
	var flags []flagInfo
	local.VisitAll(func(f *pflagFlag) {
		if f.Hidden || inherited.Lookup(f.Name) != nil {
			return
		}
		// Suppress an --x-id twin only when --x exists on this same command.
		// A blanket -id suffix filter would delete --checklist-id and
		// --item-id, which have no twin, making those commands uncallable
		// from the reference.
		if base, ok := strings.CutSuffix(f.Name, "-id"); ok && local.Lookup(base) != nil {
			return
		}
		flags = append(flags, describeFlag(f))
	})
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	leaf.Flags = flags
	return leaf
}

func describeFlag(f *pflagFlag) flagInfo {
	info := flagInfo{
		Name:      f.Name,
		Shorthand: f.Shorthand,
		Type:      f.Value.Type(),
		Default:   f.DefValue,
		Usage:     f.Usage,
	}
	// --timeout's DefValue is literally "0s" and means "fall back to config".
	// The usage string already carries the real default.
	if f.Name == "timeout" {
		info.Default = ""
	}
	if info.Default == "false" || info.Default == "[]" {
		info.Default = ""
	}
	return info
}

func splitAnnotation(v string) []string {
	if v == "" {
		return nil
	}
	return strings.Fields(v)
}

func renderMarkdown(globals []flagInfo, leaves []leafInfo) string {
	var b strings.Builder

	b.WriteString(generatedNotice)
	b.WriteString("\n\n# Command reference\n\n")
	b.WriteString("Every command prints one JSON envelope on stdout and exits with a code that\n")
	b.WriteString("names the recovery action. See `contract.md` for the envelope and the codes.\n\n")

	b.WriteString("Legend: **W** changes state on Trello and is refused when `TRELLO_CLI_READONLY`\n")
	b.WriteString("is set. It does not cover local files: `skills install` writes to disk and is\n")
	b.WriteString("not gated. **D** cannot be undone from this tool: it needs `--yes` and refuses\n")
	b.WriteString("a name prefix. Commands taking an object accept both `--thing` (a name) and\n")
	b.WriteString("`--thing-id` (an exact id); only the name form is listed.\n\n")
	b.WriteString("**Requires** lists what the command cannot run without. `--board` and `--list`\n")
	b.WriteString("can also be supplied by `TRELLO_CLI_BOARD` and `TRELLO_CLI_LIST`; every other\n")
	b.WriteString("required flag has to be passed.\n\n")

	b.WriteString("## Global flags\n\nAvailable on every command.\n\n")
	b.WriteString("| Flag | Type | Description |\n| --- | --- | --- |\n")
	for _, f := range globals {
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", flagLabel(f), f.Type, f.Usage))
	}

	b.WriteString("\n## Commands\n\n")
	for _, leaf := range leaves {
		b.WriteString("### `" + leaf.Path + "`")
		switch {
		case leaf.Destructive:
			b.WriteString("  **W D**")
		case leaf.Mutates:
			b.WriteString("  **W**")
		}
		b.WriteString("\n\n")
		if leaf.Short != "" {
			b.WriteString(leaf.Short + "\n\n")
		}
		// Without this a command taking a positional looked like it took none,
		// which is unrecoverable from the reference alone.
		if leaf.Args != "" {
			b.WriteString("Usage: `" + leaf.Path + " " + leaf.Args + "`\n\n")
		}
		if len(leaf.Requires) > 0 {
			b.WriteString("Requires: " + joinFlags(leaf.Requires) + "\n\n")
		}
		if len(leaf.RequiresOne) > 0 {
			b.WriteString("Requires at least one of: " + joinFlags(leaf.RequiresOne) + "\n\n")
		}
		if len(leaf.Flags) == 0 {
			b.WriteString("No flags of its own.\n\n")
			continue
		}
		b.WriteString("| Flag | Type | Default | Description |\n| --- | --- | --- | --- |\n")
		for _, f := range leaf.Flags {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", flagLabel(f), f.Type, code(f.Default), f.Usage))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func flagLabel(f flagInfo) string {
	if f.Shorthand != "" {
		return fmt.Sprintf("`-%s, --%s`", f.Shorthand, f.Name)
	}
	return "`--" + f.Name + "`"
}

func joinFlags(names []string) string {
	out := make([]string, 0, len(names))
	for _, n := range names {
		out = append(out, "`--"+n+"`")
	}
	return strings.Join(out, ", ")
}

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

// rootCommand builds the tree the reference describes.
func rootCommand() *cobra.Command {
	return cli.NewApp().NewRootCommand()
}
