// Command gencontract renders the machine contract from internal/errx.
//
// internal/errx is the single source of truth for the exit-code table. Every
// other statement of it in the repository is produced here, so a code cannot be
// renumbered in one place and left stale in another.
package main

import (
	"fmt"
	"strings"

	"github.com/abigotado/trello-cli/internal/errx"
)

// generatedNotice marks the output as machine-produced. It matches the
// convention the gofmt hook looks for, so these files are never reformatted or
// hand-edited by mistake.
const generatedNotice = "<!-- Code generated by tools/gencontract. DO NOT EDIT. -->"

// renderMarkdown produces the contract reference.
func renderMarkdown(c errx.Contract) string {
	var b strings.Builder

	b.WriteString(generatedNotice)
	b.WriteString("\n\n# Machine contract\n\n")
	b.WriteString("Regenerate with `go generate ./...`.\n\n")

	b.WriteString("## Envelope\n\n")
	b.WriteString(fmt.Sprintf("Current version: `%d`.\n\n", c.EnvelopeVersion))
	b.WriteString("```json\n")
	b.WriteString(`{"ok":true,"v":1,"data":{},"meta":{"count":3,"truncated":false}}` + "\n")
	b.WriteString(`{"ok":false,"v":1,"error":{"code":"AMBIGUOUS_BOARD","message":"","candidates":[]},"hint":"pass --board-id"}` + "\n")
	b.WriteString("```\n\n")
	b.WriteString("`ok`, `v`, `data`, `meta`, `error.code`, `error.message`, and `hint` keep their\n")
	b.WriteString("names, types, and nullability. Adding a field is additive; renaming, removing,\n")
	b.WriteString("or retyping one requires bumping `v`.\n\n")
	b.WriteString("`error.code` is a stable `SCREAMING_SNAKE_CASE` string and is where new\n")
	b.WriteString("granularity goes — prefer a new code over a new exit status.\n\n")

	b.WriteString("## Exit codes\n\n")
	b.WriteString("Each code maps to a distinct caller recovery action. If the caller's next move\n")
	b.WriteString("would be the same as an existing code's, it belongs in `error.code` instead.\n\n")
	b.WriteString("| Code | Name | Meaning | Caller's next move |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, info := range c.Codes {
		b.WriteString(fmt.Sprintf("| %d | `%s` | %s | %s |\n",
			info.Code, info.Name, info.Meaning, info.NextMove))
	}

	b.WriteString("\n## Notes\n\n")
	b.WriteString("- A compiled Go binary exits `2` when the runtime kills it, which is why `2`\n")
	b.WriteString("  means a usage error rather than anything an agent should retry. Panics are\n")
	b.WriteString("  recovered and reported as `1`.\n")
	b.WriteString("- Output defaults to `json` when stdout is not a terminal.\n")
	b.WriteString("- stdout carries only the envelope; logs and prompts go to stderr.\n")
	b.WriteString("  `--help` and `-h` are the exception: they print usage prose on stdout and\n")
	b.WriteString("  exit 0. Naming no command at all is exit 2 with an envelope, so a caller\n")
	b.WriteString("  never sees exit 0 paired with output it cannot parse.\n")
	b.WriteString("- `trello-cli contract` prints this same table as JSON at runtime.\n")

	return b.String()
}
